name: Lint and Build docs
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Lint and Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Lint and Build docs
        uses: JMadgwick/mkdocs-deploy-gh-pages@oi-pr
        env:
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
