name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - add-pr+pdf

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: JMadgwick/mkdocs-deploy-gh-pages@pdf-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.openindiana.org
          CONFIG_FILE: mkdocs.yml
